### PR TITLE
Don't include local classes

### LINKED ISSUE #654: Discovery phase of SpekTestEngine fails for nested class inside Spek tests
This is related to https://github.com/spekframework/spek/issues/642 but I still have a problem running tests with Spek `2.0.1` from CLI.

```kotlin

class SampleTest : Spek({
  class NestedClass {
    // ...
  }

  Feature("sample feature") {
    // Scenario, When, Then inside this block...
  }
})
```

This will produce the following output in standard error: it seems SpekTestEngine fails during discovery phase for getting `null` from KClass#qualifiedName.

```
Gradle Test Executor 1 STANDARD_ERROR
    org.junit.platform.launcher.core.DefaultLauncher handleThrowable
    Warning: TestEngine with ID 'spek2' failed to discover tests
    java.lang.IllegalStateException: Required value was null.
        at org.spekframework.spek2.runtime.util.ClassUtil.extractPackageAndClassNames(ClassUtil.kt:7)
        at org.spekframework.spek2.runtime.scope.PathBuilder$Companion.from(Path.kt:99)
        at org.spekframework.spek2.junit.SpekTestEngine.discover(SpekTestEngine.kt:53)
        at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:130)
        at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:117)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:92)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$100(JUnitPlatformTestClassProcessor.java:77)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:73)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy2.stop(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:131)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by KeithYokoma**
Resolves #654.

[KClass#qualifiedName](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.reflect/-k-class/qualified-name.html) returns null if the class is local or anonymous object literal but [`PathBuilder.from(KClass)`](https://github.com/spekframework/spek/blob/e7d76336473af50f8d9d1f116749a6a5a7bea43d/spek-runtime/src/commonMain/kotlin/org/spekframework/spek2/runtime/scope/Path.kt#L98) requires the `KClass#qualifiedName` returns non-null string so `SpekTestEngine` fails during test discovery.

### CODE REVIEW

**Comment by raniejade** [comment]
@KeithYokoma thanks, but this is already fixed in master. The exception on #654 is happening on `SpekRuntime#discover`. local classes are never passed to `ClassSelector`s. Can you use the latest dev build: https://bintray.com/spekframework/spek-dev/spek2/2.1.0-alpha.0.3%2Bc70a3c3 and confirm that it works?

**Comment by KeithYokoma** [comment]
Thanks for quick response and Yes, I've tried that one but it still doesn't work for the same reason. I think `SpekRuntime#discover` runs after building `classSelectors` and the failure happens [here](https://github.com/spekframework/spek/blob/2.x/spek-runner/junit5/src/main/kotlin/org/spekframework/spek2/junit/SpekTestEngine.kt#L53).

**Comment by raniejade** [comment]
Right, but we don't ever pass local classes to `classSelectors` so I don't see why it's happening. Can you paste in a stacktrace? Or better yet a sample project that replicates the issue.

**Comment by KeithYokoma** [comment]
https://github.com/keithyokoma/spek2sample

Here is the sample project. Sorry I should have provided more detail about the project but the issue is on the Android project so hitting `./gradlew testDebugUnitTest` will fail and generated test report includes nothing.

```
Successfully started process 'Gradle Test Executor 1'

Gradle Test Executor 1 STANDARD_ERROR
    org.junit.platform.launcher.core.DefaultLauncher handleThrowable
    Warning: TestEngine with ID 'spek2' failed to discover tests
    java.lang.IllegalStateException: Required value was null.
        at org.spekframework.spek2.runtime.util.ClassUtil.extractPackageAndClassNames(ClassUtil.kt:7)
        at org.spekframework.spek2.runtime.scope.PathBuilder$Companion.from(Path.kt:99)
        at org.spekframework.spek2.junit.SpekTestEngine.discover(SpekTestEngine.kt:53)
        at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:130)
        at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:117)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:92)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$100(JUnitPlatformTestClassProcessor.java:77)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:73)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy2.stop(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:131)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)

Finished generating test XML results (0.001 secs) into: /path/to/Spek2Sample/app/build/test-results/testDebugUnitTest
Generating HTML test report...
Finished generating test html results (0.016 secs) into: /path/to/Spek2Sample/app/build/reports/tests/testDebugUnitTest
:app:testDebugUnitTest (Thread[Task worker for ':' Thread 19,5,main]) completed. Took 0.611 secs.

```

**Comment by raniejade** [comment]
Thanks for the sample project! I'll take a look.

File: spek-runner/junit5/src/main/kotlin/org/spekframework/spek2/junit/SpekTestEngine.kt [hunk 1]
```diff
@@ -48,7 +48,9 @@ class SpekTestEngine : TestEngine {
             .map { it.toString() }
 
         val classSelectors = discoveryRequest.getSelectorsByType(ClassSelector::class.java)
-            .map {
+            .filter {
+                it.javaClass.isLocalClass.not()
```
Comment (raniejade) [inline spek-runner/junit5/src/main/kotlin/org/spekframework/spek2/junit/SpekTestEngine.kt]: nit: `!it.javaClass.isLocalClass`

**Review by raniejade — CHANGES_REQUESTED** [review]
I see it now, thanks for the PR! Just one small nit and can you also filter out classes that is not a subtype of `Spek`?

File: spek-runner/junit5/src/main/kotlin/org/spekframework/spek2/junit/SpekTestEngine.kt (hunk 1 above)
Comment (raniejade) [reply spek-runner/junit5/src/main/kotlin/org/spekframework/spek2/junit/SpekTestEngine.kt]: maybe add a check for anonymous classes as well? Not sure if `local` == `anonymous`.

Comment (KeithYokoma) [reply spek-runner/junit5/src/main/kotlin/org/spekframework/spek2/junit/SpekTestEngine.kt]: Thanks! And I think adding a check for anonymous classes is also required so I will add it!

**Review by raniejade — APPROVED** [review]
Awesome, thanks @KeithYokoma!
