### PR TITLE
Properly handle exceptions during discovery phase

### LINKED ISSUE #176: exception in action results in green test
The error can be reproduced by the following code:

```kotlin
describe("error sceenario"){
    on("exception thrown in action block"){
        throw IllegalArgumentException("oh no...")
        test("on should be red not green"){}
    }
}
```
The `on` should not be green (I am using intellij) but red and an exception should be shown.

### PR DESCRIPTION
**Pull request by raniejade**
Ignore failing groups during discovery phase. Passing groups will now
be properly discovered by Spek.

Resolves #176.

### CODE REVIEW

File: spek-junit-platform-engine/src/test/kotlin/org/jetbrains/spek/engine/FailingGroupTest.kt [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+            group("some group") {
+                test("do something") { }
+                test("do another thing") { }
+            }
+        })
+
+        val recorder = executeTestsForClass(FailingSpec::class)
+
+        assertThat(recorder.containerFailureCount, equalTo(1))
+        assertThat(recorder.testSuccessfulCount, equalTo(2))
```
Comment (artem-zinnatullin) [inline spek-junit-platform-engine/src/test/kotlin/org/jetbrains/spek/engine/FailingGroupTest.kt]: 👍
